name: deploy docs to prod

on:
  push:
    branches: [main]

jobs:
  # pre-job:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Cancel redundant workflows
  #       uses: technote-space/auto-cancel-redundant-workflow@v1

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node 16
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - uses: pnpm/action-setup@v2
        with:
          version: 6.0.2

      - name: Install vercel
        run: pnpm i vercel -g

      - name: Format with Prettier
        run: pnpm run format

      - name: Deploy Docs
        run: vercel -f --prod --token $VERCEL_TOKEN
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_CLI_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJ }}
